# Generated by Django 5.0.6 on 2024-05-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('purchases', models.TextField(blank=True, null=True)),
                ('took_on', models.DateTimeField()),
                ('returned_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
