# Generated by Django 5.0.6 on 2024-05-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='debts_customer',
        ),
    ]
